### ISSUE TITLE
有思维导图么

### ISSUE THREAD

**Issue by Jancd** [a7a2/lottery#1]
想了解了解这个是做什么的,需要实现什么功能,怎么开始推进项目.

**Comment by a7a2** [comment]
一个彩票系统，前端抄袭https://www.cp33.com
。不过要做成可以开任意自定义赔率网站名等参数的一站式平台。就像淘宝可以开很多店铺一样，主要面向手机端，就是做成app，照炒上面那个网址即可。现在博彩业很流行。。。国内网上都关了。。。

2017年8月20日 23:45，"SergeyJay" <notifications@github.com>写道：

**Comment by a7a2** [comment]
网址是这个https://www.cai33.net

2017年8月21日 00:02，"a7a2" <me@a7a2.com>写道：

**Comment by a7a2** [comment]
现在国内线上彩票都关闭了，全部转到东南亚及澳门了。国外也有很多出名的彩票网站如https://www.thelotter.com/
，我本人自学go两年不到总感觉自己的代码跟别人差距很大可阅性上。我博彩方面的门道不少，有能力的跟上。

2017年8月21日 00:04，"a7a2" <me@a7a2.com>写道：

**Comment by a7a2** [comment]
代码还有很多包括开奖数据采集那些及数据库设计那些还未整理进去 明天正好保证能运作。。。。

2017年8月21日 00:10，"a7a2" <me@a7a2.com>写道：

**Comment by Jancd** [comment]
谢谢,希望我也能帮点忙
