### ISSUE TITLE
啊哦。居然还有用go写的。

### ISSUE THREAD

**Issue by mainxx** [a7a2/lottery#5]
遇到问题可以向你提问吗？

**Comment by a7a2** [comment]
可以的 我最热心帮人了。。。

**Comment by mainxx** [comment]
你是正在写第二版本吗？

**Comment by a7a2** [comment]
暂时不写 找不着门路 第二个项目中～ 这份代购还差一个充值系统就完美运行的。。。那个sql备份文件自己导入到数据库。。。

**Comment by mainxx** [comment]
我是.net技术栈的，本来准备写一套。但是看到居然有GO写的，非常神奇。我也准备学GO。刚好可以用这个探路。
