### ISSUE TITLE
pgsql还原cp33.sql文件失败。

### ISSUE THREAD

**Issue by mainxx** [a7a2/lottery#7]
我有时间我就鼓捣你的项目。上次还原好像失败了。
这次也失败了。
使用命令：
pg_restore -c -U postgres -W -d cp33  E:\cp33\cp33-end\cp33.sql 

![qq 20171226173413](https://user-images.githubusercontent.com/14832636/34354057-ac2521c8-ea66-11e7-959e-d09c8f7fd939.png)

**Comment by a7a2** [comment]
这些是索引 自己手动使用pgadmin自己添加 ，尽可能使用brin 包括uuid也使用brin

2017年12月26日星期二，joven <notifications@github.com> 写道：

**Comment by mainxx** [comment]
啥意思？可是我连表都没有看见啊。是不是我执行这个命令是错的。

**Comment by a7a2** [comment]
自己使用编辑器打开删除该语句 或者在其他系统如mac os，windows上试试 最好最新版本的10.1

**Comment by mainxx** [comment]
你那个文件是二进制的，还是sql文本。我只需要执行就可以了吗？我看到好多乱码。编码是什么格式的？
